spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://47.102.192.219:3306/baoli?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 12 #连接池最大连接数
      connection-timeout: 60000 #连接超时时间
      minimum-idle: 10 #最小空闲连接
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 192.168.88.133
    username: baoli
    password: baoli
    virtual-host: /baoli
    listener:
      direct:
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 5 #每间隔5s，向服务端发送一次心跳，证明自己依然”存活“