server:
  port: 10010
spring:
  application:
    name: baoli-gateway
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    main-service: /m/**
    ucenter-service: /u/**
  ignored-services:
#  add-host-header: true #携带请求本身的head头信息
  sensitive-headers:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 20000
baoli:
  jwt:
    key: ys%baoli%2019
    expiration: 12
  filter:
    allowPaths:
      - /api/m
      - /api/u/ums/user/sms
      - /api/u/ums/user/register
      - /api/u/ums/user/login
      - /api/u/ums/user/wxapp
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 20000
  SocketTimeout: 20000